require 'rspec-puppet/matcher_helpers'
require 'rspec-puppet/support_copy'
require 'rspec-puppet-yaml/data_helpers'
require 'rspec-puppet-yaml/extenders'
require 'rspec-puppet-yaml/parser'
require 'yaml'
